# permissions to do viewer kfclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kfcluster-viewer-role
rules:
- apiGroups:
  - cluster.kubeflow.org
  resources:
  - kfclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.kubeflow.org
  resources:
  - kfclusters/status
  verbs:
  - get
