# permissions to do edit kfclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kfcluster-editor-role
rules:
- apiGroups:
  - cluster.kubeflow.org
  resources:
  - kfclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.kubeflow.org
  resources:
  - kfclusters/status
  verbs:
  - get
  - patch
  - update
