apiVersion: cluster.kubeflow.org/v1alpha1
kind: KfCluster
metadata:
  name: kfcluster-existing
spec:
  kfconfig: "https://raw.githubusercontent.com/kubeflow/kubeflow/master/bootstrap/config/kfctl_k8s_istio.yaml"
  version: "latest"
  buildkfctl: false
  platform: "generic"
  clusterprovider:
    generic:
