apiVersion: cluster.kubeflow.org/v1alpha1
kind: KfCluster
metadata:
  name: kf-action
spec:
  kf_version: latest
  config_map_name: kf-cluster-config
  platform: gcp
  apps:
    - jupyter
    - tfoperator
    - seldon
